export const ADD_USER_WALLETS = 'ADD_USER_WALLETS';
export const ADD_USER_WATCHLIST = 'ADD_USER_WATCHLIST';
export const ADD_ALERT = 'ADD_ALERT';
export const TOGGLE_TELEGRAM_NOTIFICATIONS = 'TOGGLE_TELEGRAM_NOTIFICATIONS';
